env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/acestream
  tag: latest@sha256:91074605720285cda053a34355b4a6e8e2f5719456de169d56615b853a8f521c
persistence:
  acestreamcache:
    enabled: true
    mountPath: /srv/acestream/.ACEStream
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8008
        protocol: TCP
        targetPort: 6878

portal:
  enabled: true
