image:
  repository: tccr.io/truecharts/eclipse-mosquitto
  tag: 2.0.15@sha256:6518ae763d40841e19f86cf845a3014ce2e927bb175de38fe81efc77f77ea294
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 1883
        targetPort: 1883
  websockets:
    enabled: true
    ports:
      websockets:
        enabled: true
        port: 9001
        targetPort: 9001

ingress:
  websockets:
    autoLink: true

auth:
  # -- By enabling this, `allow_anonymous` gets set to `false` in the mosquitto config.
  enabled: false

websockets:
  # -- By enabling this, an additional listener with protocol websockets is added in the mosquitto config.
  enabled: false

configmap:
  config:
    enabled: true
    data:
      mosquitto.conf: |
        listener {{ .Values.service.main.ports.main.targetPort }}
        {{- if .Values.websockets.enabled }}
        listener {{ .Values.service.websockets.ports.websockets.targetPort }}
        protocol websockets
        {{- end }}
        {{- if .Values.auth.enabled }}
        allow_anonymous false
        {{- else }}
        allow_anonymous true
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        persistence true
        persistence_location {{ .Values.persistence.data.mountPath }}
        autosave_interval 1800
        {{- end }}
        {{- if .Values.persistence.configinc.enabled }}
        include_dir {{ .Values.persistence.configinc.mountPath }}
        {{- end }}

persistence:
  data:
    enabled: true
    mountPath: "/mosquitto/data"
  configinc:
    enabled: true
    mountPath: "/mosquitto/configinc"
  mosquitto-config:
    enabled: "true"
    mountPath: "/mosquitto/config/mosquitto.conf"
    subPath: "mosquitto.conf"
    type: "custom"
    volumeSpec:
      configMap:
        name: '{{ template "tc.common.names.fullname" . }}-config'

portal:
  enabled: false
