image:
  repository: tccr.io/truecharts/alist
  pullPolicy: IfNotPresent
  tag: 3.0.2@sha256:732e61b190b6d98c96783987086dffea0b5499e695265a807f3f75eecde26f26

service:
  main:
    ports:
      main:
        targetPort: 5244
        port: 10167

persistence:
  data:
    enabled: true
    mountPath: "/opt/alist/data"

portal:
  enabled: true
