apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.6.4
deprecated: false
description: Media display for Plex, Sonarr and Radarr.
home: https://truecharts.org/docs/charts/stable/posterr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/posterr.png
keywords:
  - posterr
  - MediaServer-Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: posterr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/posterr
  - https://github.com/petersem/posterr
  - https://hub.docker.com/r/petersem/posterr/
type: application
version: 1.0.0
annotations:
  truecharts.org/catagories: |
    - MediaServer-Other
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
