env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cloudbeaver
  tag: latest@sha256:01c396762cb3d85821bb330d1a9267d0b98f81672cda27c0d86daa245d25b869
persistence:
  appdata:
    enabled: true
    mountPath: /opt/cloudbeaver/workspace
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8978
        protocol: TCP
        targetPort: 8978

portal:
  enabled: true
